services:
  - type: web
    name: comucole-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: develop
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "gemini-1.0-pro"
      - key: PYTHONUNBUFFERED
        value: "1"
