services:
  - type: postgres
    name: comucole-db
    plan: free
    region: oregon
    databaseName: comucole_db_70su
    user: comucole_user

  - type: web
    name: comucole-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: develop
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: "gemini-1.0-pro"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: comucole-db
          property: connectionString
